// File generated from our OpenAPI spec by Stainless.

package io.clearstreet.studio.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class RegtMarginSimulationTest {

    @Test
    fun createRegtMarginSimulation() {
        val regtMarginSimulation =
            RegtMarginSimulation.builder()
                .after(
                    RegtMargin.builder()
                        .dayTradeBuyingPower(42.23)
                        .effectiveRequirement(42.23)
                        .exchangeRequirement(42.23)
                        .groups(
                            listOf(
                                RegtMargin.Group.builder()
                                    .effectiveRequirement(42.23)
                                    .exchangeRequirement(42.23)
                                    .houseRequirement(42.23)
                                    .marginPercent(42.23)
                                    .marginPercentContribution(42.23)
                                    .marketValue(42.23)
                                    .marketValuePercent(42.23)
                                    .members(
                                        listOf(
                                            RegtMargin.Group.Member.builder()
                                                .assetClass(
                                                    RegtMargin.Group.Member.AssetClass.OTHER
                                                )
                                                .marketValue(42.23)
                                                .marketValuePercent(42.23)
                                                .quantity("x")
                                                .symbol("AAPL")
                                                .build()
                                        )
                                    )
                                    .name("name")
                                    .build()
                            )
                        )
                        .houseExcess(42.23)
                        .houseRequirement(42.23)
                        .netMarketValue(42.23)
                        .overnightBuyingPower(42.23)
                        .sma(42.23)
                        .sodBuyingPower(42.23)
                        .timestamp(1710613560668L)
                        .version("version")
                        .effectiveExcess(42.23)
                        .exchangeExcess(42.23)
                        .build()
                )
                .before(
                    RegtMargin.builder()
                        .dayTradeBuyingPower(42.23)
                        .effectiveRequirement(42.23)
                        .exchangeRequirement(42.23)
                        .groups(
                            listOf(
                                RegtMargin.Group.builder()
                                    .effectiveRequirement(42.23)
                                    .exchangeRequirement(42.23)
                                    .houseRequirement(42.23)
                                    .marginPercent(42.23)
                                    .marginPercentContribution(42.23)
                                    .marketValue(42.23)
                                    .marketValuePercent(42.23)
                                    .members(
                                        listOf(
                                            RegtMargin.Group.Member.builder()
                                                .assetClass(
                                                    RegtMargin.Group.Member.AssetClass.OTHER
                                                )
                                                .marketValue(42.23)
                                                .marketValuePercent(42.23)
                                                .quantity("x")
                                                .symbol("AAPL")
                                                .build()
                                        )
                                    )
                                    .name("name")
                                    .build()
                            )
                        )
                        .houseExcess(42.23)
                        .houseRequirement(42.23)
                        .netMarketValue(42.23)
                        .overnightBuyingPower(42.23)
                        .sma(42.23)
                        .sodBuyingPower(42.23)
                        .timestamp(1710613560668L)
                        .version("version")
                        .effectiveExcess(42.23)
                        .exchangeExcess(42.23)
                        .build()
                )
                .createdAt(1710613560668L)
                .name("name")
                .simulationId("6460030d-8ed4-19d3-818e-e87b36e90005")
                .build()
        assertThat(regtMarginSimulation).isNotNull
        assertThat(regtMarginSimulation.after())
            .isEqualTo(
                RegtMargin.builder()
                    .dayTradeBuyingPower(42.23)
                    .effectiveRequirement(42.23)
                    .exchangeRequirement(42.23)
                    .groups(
                        listOf(
                            RegtMargin.Group.builder()
                                .effectiveRequirement(42.23)
                                .exchangeRequirement(42.23)
                                .houseRequirement(42.23)
                                .marginPercent(42.23)
                                .marginPercentContribution(42.23)
                                .marketValue(42.23)
                                .marketValuePercent(42.23)
                                .members(
                                    listOf(
                                        RegtMargin.Group.Member.builder()
                                            .assetClass(RegtMargin.Group.Member.AssetClass.OTHER)
                                            .marketValue(42.23)
                                            .marketValuePercent(42.23)
                                            .quantity("x")
                                            .symbol("AAPL")
                                            .build()
                                    )
                                )
                                .name("name")
                                .build()
                        )
                    )
                    .houseExcess(42.23)
                    .houseRequirement(42.23)
                    .netMarketValue(42.23)
                    .overnightBuyingPower(42.23)
                    .sma(42.23)
                    .sodBuyingPower(42.23)
                    .timestamp(1710613560668L)
                    .version("version")
                    .effectiveExcess(42.23)
                    .exchangeExcess(42.23)
                    .build()
            )
        assertThat(regtMarginSimulation.before())
            .isEqualTo(
                RegtMargin.builder()
                    .dayTradeBuyingPower(42.23)
                    .effectiveRequirement(42.23)
                    .exchangeRequirement(42.23)
                    .groups(
                        listOf(
                            RegtMargin.Group.builder()
                                .effectiveRequirement(42.23)
                                .exchangeRequirement(42.23)
                                .houseRequirement(42.23)
                                .marginPercent(42.23)
                                .marginPercentContribution(42.23)
                                .marketValue(42.23)
                                .marketValuePercent(42.23)
                                .members(
                                    listOf(
                                        RegtMargin.Group.Member.builder()
                                            .assetClass(RegtMargin.Group.Member.AssetClass.OTHER)
                                            .marketValue(42.23)
                                            .marketValuePercent(42.23)
                                            .quantity("x")
                                            .symbol("AAPL")
                                            .build()
                                    )
                                )
                                .name("name")
                                .build()
                        )
                    )
                    .houseExcess(42.23)
                    .houseRequirement(42.23)
                    .netMarketValue(42.23)
                    .overnightBuyingPower(42.23)
                    .sma(42.23)
                    .sodBuyingPower(42.23)
                    .timestamp(1710613560668L)
                    .version("version")
                    .effectiveExcess(42.23)
                    .exchangeExcess(42.23)
                    .build()
            )
        assertThat(regtMarginSimulation.createdAt()).isEqualTo(1710613560668L)
        assertThat(regtMarginSimulation.name()).isEqualTo("name")
        assertThat(regtMarginSimulation.simulationId())
            .isEqualTo("6460030d-8ed4-19d3-818e-e87b36e90005")
    }
}
